##MYSQL
#spring.user.datasource.jdbcUrl=jdbc:mysql://localhost:3306/datasource1
#spring.user.datasource.username=root
#spring.user.datasource.password=Password
#spring.user.datasource.driver-class-name=com.mysql.jdbc.Driver
#
#spring.jpa.show-sql = true
#
##Oracle
#spring.book.datasource.jdbcUrl=jdbc:mysql://localhost:3306/datasource2
#spring.book.datasource.username=root
#spring.book.datasource.password=Password
#spring.book.datasource.driver-class-name=com.mysql.jdbc.Driver
#
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#logging.file.path=customlogs-folder/
logging.file.name=customlogs-folder/myLogs.log
log4j.appender.file.MaxFileSize=10MB
log4j.appender.file.MaxBackupIndex=10

#####LOGGING. . . .
#logging.level.org.springframework.web=ERROR
#logging.level.com.example.*=TRACE
# Print only messages of level ERROR or above in the package noModule.
log4j.logger.noModule=DEBUG

# Logging pattern for the console
logging.pattern.console="%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Logging pattern for file
logging.pattern.file= "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details=always
#management.endpoints.web.base-path=/
management.server.port=8089
